# Generated by Django 5.2.14 on 2026-05-30 17:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_permission_role_emailverificationtoken_and_more"),
        ("auth", "0012_alter_user_first_name_max_length"),
        ("exams", "0001_initial"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="user",
            name="accounts_us_target__5cf620_idx",
        ),
        migrations.RemoveField(
            model_name="user",
            name="target_exam_id",
        ),
        migrations.AddField(
            model_name="user",
            name="target_exam",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="aspirants",
                to="exams.exam",
            ),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["target_exam"], name="accounts_us_target__5cf620_idx"
            ),
        ),
    ]
