# Generated by Django 5.2.14 on 2026-05-30 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_remove_user_accounts_us_target__5cf620_idx_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="userrole",
            name="uq_user_role_institution",
        ),
        migrations.AddConstraint(
            model_name="userrole",
            constraint=models.UniqueConstraint(
                condition=models.Q(("institution_id__isnull", False)),
                fields=("user", "role", "institution_id"),
                name="uq_user_role_institution_scoped",
            ),
        ),
        migrations.AddConstraint(
            model_name="userrole",
            constraint=models.UniqueConstraint(
                condition=models.Q(("institution_id__isnull", True)),
                fields=("user", "role"),
                name="uq_user_role_global",
            ),
        ),
    ]
