# Generated by Django 5.2.14 on 2026-06-24 06:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CreditBalance",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "available_credits",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "reserved_credits",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "lifetime_credits",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="credit_balance",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "credit_balances",
                "indexes": [
                    models.Index(fields=["updated_at"], name="ix_credit_bal_updated")
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("available_credits__gte", 0)),
                        name="ck_credit_available_non_negative",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("reserved_credits__gte", 0)),
                        name="ck_credit_reserved_non_negative",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("lifetime_credits__gte", 0)),
                        name="ck_credit_lifetime_non_negative",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="CreditLedger",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("grant", "Grant"),
                            ("debit", "Debit"),
                            ("reservation", "Reservation"),
                            ("release", "Release"),
                            ("adjustment", "Adjustment"),
                        ],
                        max_length=20,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("balance_after", models.DecimalField(decimal_places=2, max_digits=12)),
                ("description", models.TextField(blank=True, default="")),
                ("reference_id", models.UUIDField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="credit_ledger_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "credit_ledger",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-created_at"],
                        name="ix_credit_ledger_user_time",
                    ),
                    models.Index(
                        fields=["transaction_type"], name="ix_credit_ledger_type"
                    ),
                ],
            },
        ),
    ]
