# Generated by Django 5.2.14 on 2026-05-30 17:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("questions", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ContentApproval",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "approval_level",
                    models.CharField(
                        choices=[("reviewer", "Reviewer"), ("sme", "SME")],
                        max_length=10,
                    ),
                ),
                ("note", models.TextField(blank=True, null=True)),
                ("approved_at", models.DateTimeField(auto_now_add=True)),
                (
                    "approver",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="approvals",
                        to="questions.question",
                    ),
                ),
            ],
            options={
                "verbose_name": "Content Approval",
                "verbose_name_plural": "Content Approvals",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("question", "approval_level"),
                        name="uq_approval_question_level",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ContentReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("actor_role", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("submit", "Submit"),
                            ("claim", "Claim"),
                            ("edit", "Edit"),
                            ("approve", "Approve"),
                            ("reject", "Reject"),
                            ("request_sme", "Request SME"),
                            ("publish", "Publish"),
                            ("audit_flag", "Audit Flag"),
                        ],
                        max_length=20,
                    ),
                ),
                ("from_status", models.CharField(blank=True, max_length=20, null=True)),
                ("to_status", models.CharField(blank=True, max_length=20, null=True)),
                ("comment", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "ai_generated_question",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="questions.aigeneratedquestion",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="questions.question",
                    ),
                ),
            ],
            options={
                "verbose_name": "Content Review",
                "verbose_name_plural": "Content Reviews",
                "indexes": [
                    models.Index(
                        fields=["question", "created_at"],
                        name="content_rev_questio_44d169_idx",
                    ),
                    models.Index(
                        fields=["actor"], name="content_rev_actor_i_f765b5_idx"
                    ),
                ],
            },
        ),
    ]
