# Generated by Django 5.2.14 on 2026-05-31 15:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("attempts", "0001_initial"),
        ("exams", "0002_alter_exam_difficulty_levels"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AttemptSectionAnalytics",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "scope_type",
                    models.CharField(
                        choices=[("subject", "subject"), ("topic", "topic")],
                        max_length=10,
                    ),
                ),
                ("scope_id", models.UUIDField()),
                ("total", models.IntegerField(default=0)),
                ("correct", models.IntegerField(default=0)),
                (
                    "accuracy",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "avg_time",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                (
                    "attempt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="section_analytics",
                        to="attempts.examattempt",
                    ),
                ),
            ],
            options={
                "verbose_name": "Attempt Section Analytics",
                "verbose_name_plural": "Attempt Section Analytics",
                "db_table": "attempt_section_analytics",
                "indexes": [
                    models.Index(fields=["attempt"], name="ix_asa_attempt"),
                    models.Index(
                        fields=["scope_type", "scope_id"], name="ix_asa_scope"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ExamReadinessScore",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("score", models.DecimalField(decimal_places=2, max_digits=5)),
                ("components", models.JSONField(default=dict)),
                ("computed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "exam",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="readiness_scores",
                        to="exams.exam",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="readiness_scores",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Exam Readiness Score",
                "verbose_name_plural": "Exam Readiness Scores",
                "db_table": "exam_readiness_scores",
                "indexes": [
                    models.Index(
                        fields=["user", "exam", "-computed_at"],
                        name="ix_readiness_user",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="UserTopicPerformance",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("attempts", models.IntegerField(default=0)),
                ("correct", models.IntegerField(default=0)),
                (
                    "success_rate",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "avg_time",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
                ("last_practiced_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "exam",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="topic_performances",
                        to="exams.exam",
                    ),
                ),
                (
                    "topic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_performances",
                        to="exams.topic",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="topic_performances",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Topic Performance",
                "verbose_name_plural": "User Topic Performances",
                "db_table": "user_topic_performance",
                "indexes": [
                    models.Index(
                        fields=["user", "success_rate"], name="ix_utp_user_rate"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "topic"), name="uq_utp_user_topic"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="WeakTopic",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("accuracy", models.DecimalField(decimal_places=2, max_digits=5)),
                ("severity", models.SmallIntegerField(default=1)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("improving", "Improving"),
                            ("resolved", "Resolved"),
                        ],
                        default="active",
                        max_length=12,
                    ),
                ),
                ("detected_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "exam",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="weak_topics",
                        to="exams.exam",
                    ),
                ),
                (
                    "topic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="weak_topics",
                        to="exams.topic",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="weak_topics",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Weak Topic",
                "verbose_name_plural": "Weak Topics",
                "db_table": "weak_topics",
                "indexes": [
                    models.Index(
                        condition=models.Q(("status", "active")),
                        fields=["user"],
                        name="ix_weak_active",
                    ),
                    models.Index(fields=["topic"], name="ix_weak_topic"),
                ],
            },
        ),
    ]
