# Generated by Django 5.2.14 on 2026-05-31 13:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("exams", "0002_alter_exam_difficulty_levels"),
        ("questions", "0002_add_claimed_by_to_question"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MockTest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=180)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("system", "System"),
                            ("previous_year", "Previous Year"),
                            ("custom", "Custom"),
                        ],
                        max_length=20,
                    ),
                ),
                ("duration_seconds", models.IntegerField()),
                ("total_questions", models.IntegerField()),
                ("config", models.JSONField(default=dict)),
                ("is_published", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_mock_tests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "exam",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mock_tests",
                        to="exams.exam",
                    ),
                ),
                (
                    "previous_year_paper",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="mock_tests",
                        to="exams.previousyearpaper",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ExamAttempt",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "attempt_type",
                    models.CharField(
                        choices=[
                            ("topic", "Topic"),
                            ("subject", "Subject"),
                            ("mixed", "Mixed"),
                            ("previous_year", "Previous Year"),
                            ("full_mock", "Full Mock"),
                            ("daily", "Daily"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("created", "Created"),
                            ("in_progress", "In Progress"),
                            ("submitted", "Submitted"),
                            ("scored", "Scored"),
                        ],
                        default="created",
                        max_length=12,
                    ),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("duration_seconds", models.IntegerField(blank=True, null=True)),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("total_questions", models.IntegerField(default=0)),
                (
                    "score",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=7, null=True
                    ),
                ),
                (
                    "max_score",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=7, null=True
                    ),
                ),
                ("correct", models.IntegerField(default=0)),
                ("incorrect", models.IntegerField(default=0)),
                ("skipped", models.IntegerField(default=0)),
                (
                    "accuracy",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("time_taken_seconds", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "exam",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attempts",
                        to="exams.exam",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attempts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "mock_test",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="attempts",
                        to="attempts.mocktest",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MockTestQuestion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("position", models.IntegerField()),
                ("section", models.CharField(blank=True, max_length=60, null=True)),
                (
                    "marks",
                    models.DecimalField(decimal_places=2, default=1, max_digits=5),
                ),
                (
                    "mock_test",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="attempts.mocktest",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="mock_test_questions",
                        to="questions.question",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserAnswer",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("not_visited", "Not Visited"),
                            ("visited", "Visited"),
                            ("answered", "Answered"),
                            ("marked", "Marked"),
                            ("answered_marked", "Answered & Marked"),
                        ],
                        default="not_visited",
                        max_length=20,
                    ),
                ),
                ("is_correct", models.BooleanField(blank=True, null=True)),
                ("time_spent_seconds", models.IntegerField(default=0)),
                ("answered_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "attempt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to="attempts.examattempt",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="user_answers",
                        to="questions.question",
                    ),
                ),
                (
                    "selected_option",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="user_answers",
                        to="questions.questionoption",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="mocktest",
            index=models.Index(fields=["exam", "type"], name="ix_mt_exam_type"),
        ),
        migrations.AddIndex(
            model_name="examattempt",
            index=models.Index(fields=["user", "-created_at"], name="ix_ea_user_time"),
        ),
        migrations.AddIndex(
            model_name="examattempt",
            index=models.Index(fields=["user", "exam"], name="ix_ea_user_exam"),
        ),
        migrations.AddIndex(
            model_name="examattempt",
            index=models.Index(fields=["mock_test"], name="ix_ea_mock_test"),
        ),
        migrations.AddIndex(
            model_name="mocktestquestion",
            index=models.Index(fields=["mock_test", "position"], name="ix_mtq_order"),
        ),
        migrations.AddConstraint(
            model_name="mocktestquestion",
            constraint=models.UniqueConstraint(
                fields=("mock_test", "question"), name="uq_mtq_mock_test_question"
            ),
        ),
        migrations.AddIndex(
            model_name="useranswer",
            index=models.Index(fields=["question"], name="ix_ua_question"),
        ),
        migrations.AddConstraint(
            model_name="useranswer",
            constraint=models.UniqueConstraint(
                fields=("attempt", "question"), name="uq_ua_attempt_question"
            ),
        ),
    ]
