# Generated by Django 5.2.14 on 2026-06-16 14:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attempts", "0001_initial"),
        ("exams", "0002_alter_exam_difficulty_levels"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="examattempt",
            index=models.Index(
                condition=models.Q(("status", "in_progress")),
                fields=["status", "started_at"],
                name="ix_ea_expiry_scan",
            ),
        ),
    ]
