# Generated by Django 5.2.14 on 2026-06-20 16:07

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CMSPage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("slug", models.SlugField(max_length=200)),
                ("title", models.CharField(max_length=255)),
                ("meta_title", models.CharField(blank=True, max_length=255)),
                ("meta_description", models.TextField(blank=True)),
                (
                    "locale",
                    models.CharField(
                        choices=[
                            ("as", "Assamese"),
                            ("en", "English"),
                            ("hi", "Hindi"),
                        ],
                        default="as",
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "Draft"), ("published", "Published")],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "CMS Page",
                "verbose_name_plural": "CMS Pages",
                "ordering": ["-updated_at"],
                "indexes": [
                    models.Index(
                        fields=["slug", "locale"], name="cms_cmspage_slug_1d9bf6_idx"
                    ),
                    models.Index(
                        fields=["status"], name="cms_cmspage_status_219e45_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("slug", "locale"), name="uniq_cmspage_slug_locale"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="CMSBlock",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "block_type",
                    models.CharField(
                        choices=[
                            ("hero", "Hero"),
                            ("rich_text", "Rich Text"),
                            ("faq", "FAQ"),
                            ("cta", "CTA"),
                        ],
                        max_length=20,
                    ),
                ),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("content", models.JSONField(blank=True, default=dict)),
                (
                    "page",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blocks",
                        to="cms.cmspage",
                    ),
                ),
            ],
            options={
                "verbose_name": "CMS Block",
                "verbose_name_plural": "CMS Blocks",
                "ordering": ["sort_order", "id"],
                "indexes": [
                    models.Index(
                        fields=["page", "sort_order"],
                        name="cms_cmsbloc_page_id_455329_idx",
                    )
                ],
            },
        ),
    ]
