# Generated by Django 5.2.14 on 2026-06-20 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cmspage",
            name="category",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="cmspage",
            name="page_type",
            field=models.CharField(
                choices=[("page", "Page"), ("guide", "Guide")],
                default="page",
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="cmspage",
            index=models.Index(
                fields=["page_type", "status"], name="cms_cmspage_page_ty_dbb3ef_idx"
            ),
        ),
    ]
