# Generated by Django 5.2.14 on 2026-05-30 17:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Subtopic",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("position", models.IntegerField(default=0)),
            ],
            options={
                "ordering": ["topic", "position"],
            },
        ),
        migrations.CreateModel(
            name="Exam",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("code", models.CharField(max_length=40, unique=True)),
                ("name", models.CharField(max_length=150)),
                (
                    "exam_type",
                    models.CharField(
                        choices=[
                            ("qualifying", "Qualifying"),
                            ("ranked", "Ranked"),
                            ("entrance", "Entrance"),
                        ],
                        max_length=20,
                    ),
                ),
                ("difficulty_levels", models.JSONField(default=list)),
                ("exam_rules", models.JSONField(default=dict)),
                ("blueprint", models.JSONField(default=dict)),
                ("passing_criteria", models.JSONField(default=dict)),
                ("analytics_rules", models.JSONField(default=dict)),
                ("audience_is_minor", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Exam",
                "verbose_name_plural": "Exams",
                "indexes": [
                    models.Index(
                        fields=["is_active"], name="exams_exam_is_acti_1c1d9c_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Subject",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("position", models.IntegerField(default=0)),
                (
                    "exam",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subjects",
                        to="exams.exam",
                    ),
                ),
            ],
            options={
                "ordering": ["exam", "position"],
            },
        ),
        migrations.CreateModel(
            name="Topic",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("position", models.IntegerField(default=0)),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="topics",
                        to="exams.subject",
                    ),
                ),
            ],
            options={
                "ordering": ["subject", "position"],
            },
        ),
        migrations.CreateModel(
            name="SyllabusItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "weightage",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("position", models.IntegerField(default=0)),
                (
                    "exam",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="syllabus_items",
                        to="exams.exam",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="exams.syllabusitem",
                    ),
                ),
                (
                    "subtopic",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="exams.subtopic",
                    ),
                ),
                (
                    "topic",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="exams.topic",
                    ),
                ),
            ],
            options={
                "verbose_name": "Syllabus Item",
                "verbose_name_plural": "Syllabus Items",
            },
        ),
        migrations.AddField(
            model_name="subtopic",
            name="topic",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subtopics",
                to="exams.topic",
            ),
        ),
        migrations.CreateModel(
            name="PreviousYearPaper",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("code", models.CharField(max_length=60)),
                ("year", models.IntegerField()),
                ("language", models.CharField(default="as", max_length=10)),
                ("file_path", models.TextField(blank=True, null=True)),
                ("total_questions", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "exam",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="previous_year_papers",
                        to="exams.exam",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Previous Year Paper",
                "verbose_name_plural": "Previous Year Papers",
                "indexes": [
                    models.Index(
                        fields=["exam", "year"], name="exams_previ_exam_id_65ef4d_idx"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("exam", "year", "code"), name="uq_pyp_exam_year_code"
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="subject",
            constraint=models.UniqueConstraint(
                fields=("exam", "name"), name="uq_subject_exam_name"
            ),
        ),
        migrations.AddConstraint(
            model_name="topic",
            constraint=models.UniqueConstraint(
                fields=("subject", "name"), name="uq_topic_subject_name"
            ),
        ),
        migrations.AddIndex(
            model_name="syllabusitem",
            index=models.Index(fields=["exam"], name="exams_sylla_exam_id_c5c1cb_idx"),
        ),
        migrations.AddIndex(
            model_name="syllabusitem",
            index=models.Index(
                fields=["parent"], name="exams_sylla_parent__c9a4b9_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="subtopic",
            constraint=models.UniqueConstraint(
                fields=("topic", "name"), name="uq_subtopic_topic_name"
            ),
        ),
    ]
