# Generated by Django 5.2.14 on 2026-05-30 19:45

import exams.models.exam
from django.db import migrations, models


class PostgreSQLOnlySQL(migrations.RunSQL):
    """RunSQL that only executes on PostgreSQL (skips SQLite test DBs)."""

    def database_forwards(self, app_label, schema_editor, from_state, to_state):
        if schema_editor.connection.vendor == "postgresql":
            super().database_forwards(app_label, schema_editor, from_state, to_state)

    def database_backwards(self, app_label, schema_editor, from_state, to_state):
        if schema_editor.connection.vendor == "postgresql":
            super().database_backwards(app_label, schema_editor, from_state, to_state)


class Migration(migrations.Migration):

    dependencies = [
        ("exams", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exam",
            name="difficulty_levels",
            field=models.JSONField(default=exams.models.exam._default_difficulty_levels),
        ),
        PostgreSQLOnlySQL(
            sql="ALTER TABLE exams_exam ALTER COLUMN difficulty_levels SET DEFAULT '[\"easy\", \"medium\", \"hard\"]'::jsonb;",
            reverse_sql="ALTER TABLE exams_exam ALTER COLUMN difficulty_levels SET DEFAULT '[]'::jsonb;",
        ),
    ]
