# Generated by Django 5.2.14 on 2026-06-20 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exams", "0002_alter_exam_difficulty_levels"),
    ]

    operations = [
        migrations.AddField(
            model_name="exam",
            name="description",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="exam",
            name="exam_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="exam",
            name="slug",
            field=models.SlugField(blank=True, max_length=160, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="exam",
            name="target_audience",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
