# Generated by Django 5.2.14 on 2026-07-01 15:25

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AIRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("groq", "Groq"),
                            ("openai", "OpenAI"),
                            ("anthropic", "Anthropic Claude"),
                            ("gemini", "Google Gemini"),
                            ("deepseek", "DeepSeek"),
                            ("mock", "Mock (no network)"),
                        ],
                        max_length=20,
                    ),
                ),
                ("model", models.CharField(max_length=100)),
                (
                    "prompt_type",
                    models.CharField(
                        choices=[
                            ("question_generation", "Question Generation"),
                            ("question_improvement", "Question Improvement"),
                            ("question_explanation", "Question Explanation"),
                            ("question_hint", "Question Hint"),
                            ("question_translation", "Question Translation"),
                            ("distractor_generation", "Distractor Generation"),
                            ("bloom_classification", "Bloom Classification"),
                            ("difficulty_classification", "Difficulty Classification"),
                        ],
                        max_length=40,
                    ),
                ),
                ("input", models.JSONField(blank=True, default=dict)),
                ("output", models.TextField(blank=True, default="")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("success", "Success"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("latency_ms", models.PositiveIntegerField(default=0)),
                ("prompt_tokens", models.PositiveIntegerField(default=0)),
                ("completion_tokens", models.PositiveIntegerField(default=0)),
                ("total_tokens", models.PositiveIntegerField(default=0)),
                (
                    "cost",
                    models.DecimalField(decimal_places=6, default=0, max_digits=12),
                ),
                ("attempts", models.PositiveIntegerField(default=1)),
                ("error", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "AI Request",
                "verbose_name_plural": "AI Requests",
                "db_table": "ai_request",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["-created_at"], name="ix_ai_request_time"),
                    models.Index(fields=["provider"], name="ix_ai_request_provider"),
                    models.Index(fields=["prompt_type"], name="ix_ai_request_prompt"),
                    models.Index(fields=["status"], name="ix_ai_request_status"),
                    models.Index(
                        fields=["created_by", "-created_at"],
                        name="ix_ai_request_user_time",
                    ),
                ],
            },
        ),
    ]
