# Generated by Django 5.2.14 on 2026-07-02 16:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AIQuestionDraft",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("exam", models.CharField(max_length=200)),
                ("subject", models.CharField(max_length=200)),
                ("topic", models.CharField(max_length=200)),
                ("subtopic", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "question_type",
                    models.CharField(
                        choices=[
                            ("single_correct", "Single Correct MCQ"),
                            ("multi_correct", "Multiple Correct MCQ"),
                            ("assertion_reason", "Assertion Reason"),
                            ("match_the_following", "Match the Following"),
                            ("true_false", "True / False"),
                            ("case_study", "Case Study"),
                            ("passage_based", "Passage Based"),
                        ],
                        max_length=40,
                    ),
                ),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("easy", "Easy"),
                            ("medium", "Medium"),
                            ("hard", "Hard"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "bloom_level",
                    models.CharField(
                        choices=[
                            ("remember", "Remember"),
                            ("understand", "Understand"),
                            ("apply", "Apply"),
                            ("analyze", "Analyze"),
                            ("evaluate", "Evaluate"),
                            ("create", "Create"),
                        ],
                        max_length=20,
                    ),
                ),
                ("language", models.CharField(max_length=10)),
                ("stem", models.TextField()),
                ("options", models.JSONField(default=list)),
                (
                    "correct_answer",
                    models.CharField(blank=True, default="", max_length=10),
                ),
                ("explanation", models.TextField(blank=True, default="")),
                ("learning_objective", models.TextField(blank=True, default="")),
                ("estimated_time", models.PositiveIntegerField(default=0)),
                ("tags", models.JSONField(default=list)),
                ("confidence", models.FloatField(blank=True, null=True)),
                ("generation_prompt", models.TextField(blank=True, default="")),
                (
                    "provider",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("groq", "Groq"),
                            ("openai", "OpenAI"),
                            ("anthropic", "Anthropic Claude"),
                            ("gemini", "Google Gemini"),
                            ("deepseek", "DeepSeek"),
                            ("mock", "Mock (no network)"),
                        ],
                        default="",
                        max_length=20,
                    ),
                ),
                ("model", models.CharField(blank=True, default="", max_length=100)),
                ("validation_report", models.JSONField(default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("reviewed", "Reviewed"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("published", "Published"),
                        ],
                        default="draft",
                        max_length=12,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ai_question_drafts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "AI Question Draft",
                "verbose_name_plural": "AI Question Drafts",
                "db_table": "ai_question_draft",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["-created_at"], name="ix_ai_draft_time"),
                    models.Index(fields=["status"], name="ix_ai_draft_status"),
                    models.Index(fields=["exam"], name="ix_ai_draft_exam"),
                    models.Index(fields=["subject"], name="ix_ai_draft_subject"),
                    models.Index(fields=["difficulty"], name="ix_ai_draft_difficulty"),
                    models.Index(fields=["language"], name="ix_ai_draft_language"),
                    models.Index(
                        fields=["created_by", "-created_at"],
                        name="ix_ai_draft_user_time",
                    ),
                ],
            },
        ),
    ]
