# Generated by Django 5.2.14 on 2026-07-02 16:51

import django.db.models.deletion
from django.db import migrations, models


def _draft_to_generated(apps, schema_editor):
    """Migrate the old default ('draft') to the reduced lifecycle ('generated')."""
    AIQuestionDraft = apps.get_model("ai", "AIQuestionDraft")
    AIQuestionDraft.objects.filter(status="draft").update(status="generated")


def _generated_to_draft(apps, schema_editor):
    AIQuestionDraft = apps.get_model("ai", "AIQuestionDraft")
    AIQuestionDraft.objects.filter(status="generated").update(status="draft")


class Migration(migrations.Migration):

    dependencies = [
        ("ai", "0002_aiquestiondraft"),
        ("questions", "0002_add_claimed_by_to_question"),
    ]

    operations = [
        migrations.RunPython(_draft_to_generated, _generated_to_draft),
        migrations.AddField(
            model_name="aiquestiondraft",
            name="imported_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="aiquestiondraft",
            name="imported_question",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="questions.question",
            ),
        ),
        migrations.AlterField(
            model_name="aiquestiondraft",
            name="status",
            field=models.CharField(
                choices=[
                    ("generated", "Generated"),
                    ("imported", "Imported"),
                    ("discarded", "Discarded"),
                ],
                default="generated",
                max_length=12,
            ),
        ),
    ]
