# Generated by Django 5.2.14 on 2026-07-02 17:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai", "0003_aiquestiondraft_imported_at_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AIGenerationJob",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=12,
                    ),
                ),
                ("progress", models.PositiveSmallIntegerField(default=0)),
                ("requested_count", models.PositiveIntegerField(default=0)),
                ("generated_count", models.PositiveIntegerField(default=0)),
                ("failed_count", models.PositiveIntegerField(default=0)),
                ("request_payload", models.JSONField(default=dict)),
                ("provider", models.CharField(blank=True, default="", max_length=20)),
                ("model", models.CharField(blank=True, default="", max_length=100)),
                ("error_message", models.TextField(blank=True, default="")),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ai_generation_jobs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "AI Generation Job",
                "verbose_name_plural": "AI Generation Jobs",
                "db_table": "ai_generation_job",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["-created_at"], name="ix_ai_job_time"),
                    models.Index(fields=["status"], name="ix_ai_job_status"),
                    models.Index(
                        fields=["created_by", "-created_at"], name="ix_ai_job_user_time"
                    ),
                ],
            },
        ),
    ]
