# Generated by Django 5.2.14 on 2026-07-02 18:46

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai", "0004_aigenerationjob"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProviderHealth",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("provider", models.CharField(max_length=20, unique=True)),
                ("success_count", models.PositiveIntegerField(default=0)),
                ("failure_count", models.PositiveIntegerField(default=0)),
                ("timeout_count", models.PositiveIntegerField(default=0)),
                ("retry_count", models.PositiveIntegerField(default=0)),
                ("last_success_at", models.DateTimeField(blank=True, null=True)),
                ("last_failure_at", models.DateTimeField(blank=True, null=True)),
                (
                    "circuit_state",
                    models.CharField(
                        choices=[
                            ("closed", "Closed"),
                            ("open", "Open"),
                            ("half_open", "Half-open"),
                        ],
                        default="closed",
                        max_length=10,
                    ),
                ),
                ("consecutive_failures", models.PositiveIntegerField(default=0)),
                ("opened_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "AI Provider Health",
                "verbose_name_plural": "AI Provider Health",
                "db_table": "ai_provider_health",
                "ordering": ["provider"],
                "indexes": [
                    models.Index(fields=["circuit_state"], name="ix_ai_health_circuit")
                ],
            },
        ),
    ]
