# Generated by Django 5.2.14 on 2026-07-03 17:39

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai", "0005_providerhealth"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="aiquestiondraft",
            name="current_version",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="aiquestiondraft",
            name="regenerated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="aiquestiondraft",
            name="regeneration_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name="AIDraftRegeneration",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("version", models.PositiveIntegerField()),
                ("is_original", models.BooleanField(default=False)),
                ("stem", models.TextField()),
                ("options", models.JSONField(default=list)),
                (
                    "correct_answer",
                    models.CharField(blank=True, default="", max_length=10),
                ),
                ("explanation", models.TextField(blank=True, default="")),
                ("difficulty", models.CharField(blank=True, default="", max_length=20)),
                (
                    "bloom_level",
                    models.CharField(blank=True, default="", max_length=20),
                ),
                ("learning_objective", models.TextField(blank=True, default="")),
                ("estimated_time", models.PositiveIntegerField(default=0)),
                ("tags", models.JSONField(default=list)),
                ("confidence", models.FloatField(blank=True, null=True)),
                ("language", models.CharField(blank=True, default="", max_length=10)),
                (
                    "question_type",
                    models.CharField(blank=True, default="", max_length=40),
                ),
                ("provider", models.CharField(blank=True, default="", max_length=20)),
                ("model", models.CharField(blank=True, default="", max_length=100)),
                ("generation_prompt", models.TextField(blank=True, default="")),
                ("feedback", models.TextField(blank=True, default="")),
                ("validation_report", models.JSONField(default=dict)),
                ("prompt_tokens", models.PositiveIntegerField(default=0)),
                ("completion_tokens", models.PositiveIntegerField(default=0)),
                ("total_tokens", models.PositiveIntegerField(default=0)),
                (
                    "cost",
                    models.DecimalField(
                        decimal_places=6, default=Decimal("0"), max_digits=12
                    ),
                ),
                ("request_id", models.CharField(blank=True, default="", max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ai_draft_regenerations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "draft",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="regenerations",
                        to="ai.aiquestiondraft",
                    ),
                ),
            ],
            options={
                "verbose_name": "AI Draft Regeneration",
                "verbose_name_plural": "AI Draft Regenerations",
                "db_table": "ai_draft_regeneration",
                "ordering": ["draft_id", "version"],
                "indexes": [
                    models.Index(
                        fields=["draft", "version"], name="ix_ai_regen_draft_ver"
                    ),
                    models.Index(
                        fields=["draft", "-created_at"], name="ix_ai_regen_draft_time"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("draft", "version"), name="uq_ai_regen_draft_version"
                    )
                ],
            },
        ),
    ]
