# Generated by Django 5.2.14 on 2026-07-03 18:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai", "0006_aiquestiondraft_current_version_and_more"),
        ("questions", "0002_add_claimed_by_to_question"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="aiquestiondraft",
            name="alignment_status",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
        migrations.AddField(
            model_name="aiquestiondraft",
            name="analysed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="aiquestiondraft",
            name="analysis_provider",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
        migrations.AddField(
            model_name="aiquestiondraft",
            name="analysis_version",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
        migrations.AddField(
            model_name="aiquestiondraft",
            name="bloom_match",
            field=models.CharField(blank=True, default="", max_length=12),
        ),
        migrations.AddField(
            model_name="aiquestiondraft",
            name="difficulty_match",
            field=models.CharField(blank=True, default="", max_length=12),
        ),
        migrations.AddField(
            model_name="aiquestiondraft",
            name="duplicate_status",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
        migrations.AddField(
            model_name="aiquestiondraft",
            name="quality_grade",
            field=models.CharField(blank=True, default="", max_length=1),
        ),
        migrations.AddField(
            model_name="aiquestiondraft",
            name="quality_report",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="aiquestiondraft",
            name="quality_score",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name="aiquestiondraft",
            index=models.Index(fields=["quality_grade"], name="ix_ai_draft_grade"),
        ),
        migrations.AddIndex(
            model_name="aiquestiondraft",
            index=models.Index(fields=["duplicate_status"], name="ix_ai_draft_dupe"),
        ),
    ]
