# Generated by Django 5.2.14 on 2026-07-03 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai", "0007_aiquestiondraft_alignment_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="aidraftregeneration",
            name="quality_after",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="aidraftregeneration",
            name="quality_before",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="aidraftregeneration",
            name="review_action",
            field=models.CharField(blank=True, default="", max_length=40),
        ),
    ]
