# Generated by Django 5.2.14 on 2026-07-03 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai", "0008_aidraftregeneration_quality_after_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="airequest",
            name="prompt_type",
            field=models.CharField(
                choices=[
                    ("question_generation", "Question Generation"),
                    ("question_improvement", "Question Improvement"),
                    ("question_explanation", "Question Explanation"),
                    ("question_hint", "Question Hint"),
                    ("question_translation", "Question Translation"),
                    ("distractor_generation", "Distractor Generation"),
                    ("bloom_classification", "Bloom Classification"),
                    ("difficulty_classification", "Difficulty Classification"),
                    ("review_improve_explanation", "Review: Improve Explanation"),
                    ("review_improve_distractors", "Review: Improve Distractors"),
                    ("review_reduce_ambiguity", "Review: Reduce Ambiguity"),
                    ("review_increase_difficulty", "Review: Increase Difficulty"),
                    ("review_reduce_difficulty", "Review: Reduce Difficulty"),
                    ("review_improve_bloom", "Review: Improve Bloom Level"),
                    ("review_rewrite_stem", "Review: Rewrite Stem"),
                    ("review_add_scenario", "Review: Add Scenario"),
                    ("review_simplify_language", "Review: Simplify Language"),
                    (
                        "review_improve_learning_objective",
                        "Review: Improve Learning Objective",
                    ),
                ],
                max_length=40,
            ),
        ),
    ]
