# Generated by Django 5.2.14 on 2026-07-04 06:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai", "0009_alter_airequest_prompt_type"),
        ("exams", "0003_exam_description_exam_exam_date_exam_slug_and_more"),
        ("questions", "0002_add_claimed_by_to_question"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AITaxonomyResolution",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("confidence", models.CharField(blank=True, default="", max_length=12)),
                ("suggestion", models.JSONField(blank=True, default=dict)),
                ("is_override", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "chosen_exam",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="exams.exam",
                    ),
                ),
                (
                    "chosen_subtopic",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="exams.subtopic",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ai_taxonomy_resolutions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "draft",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="taxonomy_resolutions",
                        to="ai.aiquestiondraft",
                    ),
                ),
                (
                    "imported_question",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="questions.question",
                    ),
                ),
                (
                    "suggested_exam",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="exams.exam",
                    ),
                ),
                (
                    "suggested_subtopic",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="exams.subtopic",
                    ),
                ),
            ],
            options={
                "verbose_name": "AI Taxonomy Resolution",
                "verbose_name_plural": "AI Taxonomy Resolutions",
                "db_table": "ai_taxonomy_resolution",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["draft", "-created_at"], name="ix_ai_taxres_draft_time"
                    ),
                    models.Index(fields=["is_override"], name="ix_ai_taxres_override"),
                ],
            },
        ),
    ]
