# Generated by Django 5.2.14 on 2026-05-30 17:06

import django.db.models.deletion
import pgvector.django.vector
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("exams", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("stem", models.TextField()),
                ("explanation", models.TextField(blank=True, null=True)),
                ("difficulty", models.SmallIntegerField(default=2)),
                ("language", models.CharField(default="as", max_length=10)),
                (
                    "origin",
                    models.CharField(
                        choices=[
                            ("official", "Official"),
                            ("ai", "AI Generated"),
                            ("manual", "Manual"),
                        ],
                        default="manual",
                        max_length=10,
                    ),
                ),
                (
                    "review_status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("in_review", "In Review"),
                            ("sme_review", "SME Review"),
                            ("approved", "Approved"),
                            ("published", "Published"),
                            ("rejected", "Rejected"),
                        ],
                        default="draft",
                        max_length=12,
                    ),
                ),
                ("tags", models.JSONField(default=dict)),
                (
                    "embedding",
                    pgvector.django.vector.VectorField(
                        blank=True, dimensions=1024, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "exam",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="exams.exam",
                    ),
                ),
                (
                    "subtopic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="questions",
                        to="exams.subtopic",
                    ),
                ),
                (
                    "verified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AiGeneratedQuestion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("generation_batch", models.UUIDField(blank=True, null=True)),
                ("model_used", models.CharField(max_length=60)),
                ("prompt", models.TextField(blank=True, null=True)),
                ("constraints_snapshot", models.JSONField(default=dict)),
                ("raw_output", models.TextField(blank=True, null=True)),
                ("validation", models.JSONField(default=dict)),
                (
                    "credits_charged",
                    models.DecimalField(decimal_places=4, default=0, max_digits=14),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("generated", "Generated"),
                            ("validated", "Validated"),
                            ("promoted", "Promoted"),
                            ("discarded", "Discarded"),
                        ],
                        default="generated",
                        max_length=12,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "exam",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_generations",
                        to="exams.exam",
                    ),
                ),
                (
                    "subtopic",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="exams.subtopic",
                    ),
                ),
                (
                    "resulting_question",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ai_source",
                        to="questions.question",
                    ),
                ),
            ],
            options={
                "verbose_name": "AI Generated Question",
                "verbose_name_plural": "AI Generated Questions",
            },
        ),
        migrations.CreateModel(
            name="QuestionAppearance",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("year", models.IntegerField()),
                (
                    "paper",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="question_appearances",
                        to="exams.previousyearpaper",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="appearances",
                        to="questions.question",
                    ),
                ),
            ],
            options={
                "verbose_name": "Question Appearance",
                "verbose_name_plural": "Question Appearances",
            },
        ),
        migrations.CreateModel(
            name="QuestionOption",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("label", models.CharField(max_length=5)),
                ("body", models.TextField()),
                ("is_correct", models.BooleanField(default=False)),
                ("position", models.IntegerField(default=0)),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="options",
                        to="questions.question",
                    ),
                ),
            ],
            options={
                "ordering": ["question", "position"],
            },
        ),
        migrations.CreateModel(
            name="QuestionStat",
            fields=[
                (
                    "question",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="stats",
                        serialize=False,
                        to="questions.question",
                    ),
                ),
                ("attempts", models.BigIntegerField(default=0)),
                ("correct", models.BigIntegerField(default=0)),
                (
                    "success_rate",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "avg_time_seconds",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Question Stat",
                "verbose_name_plural": "Question Stats",
                "indexes": [
                    models.Index(
                        fields=["success_rate"], name="questions_q_success_ce600c_idx"
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="question",
            index=models.Index(
                fields=["exam", "subtopic", "difficulty"], name="ix_q_select"
            ),
        ),
        migrations.AddIndex(
            model_name="question",
            index=models.Index(fields=["review_status"], name="ix_q_status"),
        ),
        migrations.AddIndex(
            model_name="question",
            index=models.Index(
                condition=models.Q(("review_status", "published")),
                fields=["exam"],
                name="ix_q_published",
            ),
        ),
        migrations.AddIndex(
            model_name="aigeneratedquestion",
            index=models.Index(
                fields=["exam", "status"], name="questions_a_exam_id_18d9d4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="aigeneratedquestion",
            index=models.Index(
                fields=["resulting_question"], name="questions_a_resulti_20221c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="questionappearance",
            index=models.Index(fields=["paper"], name="questions_q_paper_i_eed172_idx"),
        ),
        migrations.AddConstraint(
            model_name="questionappearance",
            constraint=models.UniqueConstraint(
                fields=("question", "paper"), name="uq_appearance_question_paper"
            ),
        ),
        migrations.AddConstraint(
            model_name="questionoption",
            constraint=models.UniqueConstraint(
                fields=("question", "label"), name="uq_option_question_label"
            ),
        ),
    ]
